// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/oxyno-zeta/opa-center/pkg/opa-center/business/decisionlogs/models"
	models1 "github.com/oxyno-zeta/opa-center/pkg/opa-center/business/partitions/models"
	models2 "github.com/oxyno-zeta/opa-center/pkg/opa-center/business/statuses/models"
	"github.com/oxyno-zeta/opa-center/pkg/opa-center/server/graphql/utils"
)

type DecisionLogConnection struct {
	Edges    []*DecisionLogEdge `json:"edges"`
	PageInfo *utils.PageInfo    `json:"pageInfo"`
}

type DecisionLogEdge struct {
	Cursor string              `json:"cursor"`
	Node   *models.DecisionLog `json:"node"`
}

type GenericPartitionPayload struct {
	Partition *models1.Partition `json:"partition"`
}

type PartitionConnection struct {
	Edges    []*PartitionEdge `json:"edges"`
	PageInfo *utils.PageInfo  `json:"pageInfo"`
}

type PartitionEdge struct {
	Cursor string             `json:"cursor"`
	Node   *models1.Partition `json:"node"`
}

type StatusConnection struct {
	Edges    []*StatusEdge   `json:"edges"`
	PageInfo *utils.PageInfo `json:"pageInfo"`
}

type StatusEdge struct {
	Cursor string          `json:"cursor"`
	Node   *models2.Status `json:"node"`
}
