// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	models1 "github.com/oxyno-zeta/opa-center/pkg/opa-center/business/decisionlogs/models"
	"github.com/oxyno-zeta/opa-center/pkg/opa-center/business/partitions/models"
	"github.com/oxyno-zeta/opa-center/pkg/opa-center/server/graphql/utils"
)

type CreatePartitionPayload struct {
	Partition *models.Partition `json:"partition"`
}

type DecisionLogConnection struct {
	Edges    []*DecisionLogEdge `json:"edges"`
	PageInfo *utils.PageInfo    `json:"pageInfo"`
}

type DecisionLogEdge struct {
	Cursor string               `json:"cursor"`
	Node   *models1.DecisionLog `json:"node"`
}

type PartitionConnection struct {
	Edges    []*PartitionEdge `json:"edges"`
	PageInfo *utils.PageInfo  `json:"pageInfo"`
}

type PartitionEdge struct {
	Cursor string            `json:"cursor"`
	Node   *models.Partition `json:"node"`
}
