name: "Add size label"
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-18.04
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.3.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
